export enum QueryKeys {
    AddToQueue = "ADD_TO_QUEUE",
    AlbumTracks = "ALBUM_TRACKS",
    Api = "API",
    ArtistAlbums = "ARTIST_ALBUMS",
    ArtistById = "ARTIST_BY_ID",
    Credentials = "CREDENTIALS",
    ImageByItemId = "IMAGE_BY_ITEM_ID",
    Libraries = "LIBRARIES",
    Pause = "PAUSE",
    Play = "PLAY",
    Playlists = "PLAYLISTS",
    Progress = "PROGRESS",
    PlayQueue = "PLAY_QUEUE",
    PublicApi = "PUBLIC_API",
    PublicSystemInfo = "PUBLIC_SYSTEM_INFO",
    RemoveFromQueue = "REMOVE_FROM_QUEUE",
    RemoveMultipleFromQueue = "REMOVE_MULTIPLE_FROM_QUEUE",
    ReportPlaybackPosition = "REPORT_PLAYBACK_POSITION",
    ReportPlaybackStarted = "REPORT_PLAYBACK_STARTED",
    ReportPlaybackStopped = "REPORT_PLAYBACK_STOPPED",
    ServerUrl = "SERVER_URL",
}