# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    match(
      type: "appstore",
      app_identifier: "com.cosmonautical.jellify",
      readonly: true
    )
    increment_build_number(
      build_number: ENV['BUILD_NUMBER'],
      xcodeproj: "Jellify.xcodeproj"
    )
    build_app(
      scheme: "Jellify",
      workspace: "Jellify.xcworkspace", 
    )
    # http://docs.fastlane.tools/actions/upload_to_testflight/#upload_to_testflight
    upload_to_testflight(
      skip_waiting_for_build_processing: true # Required for App password support
    )
  end
end
