# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :build do 
    setup_ci
    match(
      type: "appstore",
      app_identifier: "com.cosmonautical.jellify",
      readonly: true
    )
    build_app(
      scheme: "Jellify - Release",
      workspace: "Jellify.xcworkspace"
    )
  end 

  lane :beta do
    setup_ci
    match(
      type: "appstore",
      app_identifier: "com.cosmonautical.jellify",
      readonly: true
    )

    increment_version_number(
      version_number: ENV['VERSION_NUMBER'],
      xcodeproj: "Jellify.xcodeproj"
    )

    increment_build_number(
      xcodeproj: "Jellify.xcodeproj"
    )
    build_app(
      scheme: "Jellify - Release",
      workspace: "Jellify.xcworkspace", 
    )
    # http://docs.fastlane.tools/actions/upload_to_testflight/#upload_to_testflight
    upload_to_testflight(
      api_key_path: "fastlane/appstore_connect_api_key.json",
      beta_app_feedback_email: "violet@cosmonautical.cloud",
      beta_app_description: "A music app for Jellyfin",
      expire_previous_builds: true,
      distribute_external: true,
      changelog: "Updated Sign In components, Player Optimizations, 'See More' buttons",
      groups: [
        "Selfhosters"
      ]
    )
  end
end
