// https://github.com/doublesymmetry/react-native-track-player/issues/501
jest.mock('react-native-track-player', () => {
  return {
    __esModule: true,
    default: {
      addEventListener: () => ({
        remove: jest.fn(),
      }),
      registerEventHandler: jest.fn(),
      registerPlaybackService: jest.fn(),
      setupPlayer: jest.fn(),
      destroy: jest.fn(),
      updateOptions: jest.fn(),
      reset: jest.fn(),
      add: jest.fn(),
      remove: jest.fn(),
      skip: jest.fn(),
      skipToNext: jest.fn(),
      skipToPrevious: jest.fn(),
      removeUpcomingTracks: jest.fn(),
      // playback commands
      play: jest.fn(),
      pause: jest.fn(),
      stop: jest.fn(),
      seekTo: jest.fn(),
      setVolume: jest.fn(),
      setRate: jest.fn(),
      // player getters
      getQueue: jest.fn(),
      getTrack: jest.fn(),
      getCurrentTrack: jest.fn(),
      getVolume: jest.fn(),
      getDuration: jest.fn(),
      getPosition: jest.fn(),
      getBufferedPosition: jest.fn(),
      getState: jest.fn(),
      getRate: jest.fn(),
      // constants
      constants: {
        CAPABILITY_PLAY: 1,
        CAPABILITY_PLAY_FROM_ID: 2,
        CAPABILITY_PLAY_FROM_SEARCH: 4,
        CAPABILITY_PAUSE: 8,
        CAPABILITY_STOP: 16,
        CAPABILITY_SEEK_TO: 32,
        CAPABILITY_SKIP: 64,
        CAPABILITY_SKIP_TO_NEXT: 128,
        CAPABILITY_SKIP_TO_PREVIOUS: 256,
        CAPABILITY_JUMP_FORWARD: 512,
        CAPABILITY_JUMP_BACKWARD: 1024,
        CAPABILITY_SET_RATING: 2048,
        CAPABILITY_LIKE: 4096,
        CAPABILITY_DISLIKE: 8192,
        CAPABILITY_BOOKMARK: 16384,
        CAPABILITY_SKIP_TO_QUEUE_ITEM: 32768,
        CAPABILITY_PLAY_FROM_MEDIA_ID: 65536,
        CAPABILITY_PLAY_FROM_SEARCH_WITH_EXTRAS: 131072,
        CAPABILITY_PAUSE_RESUME: 262144,
        CAPABILITY_PLAY_FROM_URI: 524288,
        CAPABILITY_PLAY_FROM_SEARCH_AND_PLAY: 1048576,
        CAPABILITY_SET_RATING_INDICATOR: 2097152,
        CAPABILITY_SET_REPEAT_MODE: 4194304,
        CAPABILITY_SET_SHUFFLE_MODE: 8388608,
        CAPABILITY_SET_SPEED: 16777216,
        CAPABILITY_SET_QUEUE: 33554432,
        CAPABILITY_SET_QUEUE_TITLE: 67108864,
        CAPABILITY_SET_QUEUE_ITEM_TITLE: 134217728,
        CAPABILITY_SET_MEDIA_ITEM_METADATA: 268435456,
        CAPABILITY_SET_MEDIA_ITEM_IMAGE: 536870912,
        CAPABILITY_SET_MEDIA_ITEM_URI: 1073741824,
        CAPABILITY_SET_MEDIA_ITEM_REPEAT_MODE: 2147483648,
        CAPABILITY_SET_MEDIA_ITEM_SHUFFLE_MODE: 4294967296,
        CAPABILITY_SET_MEDIA_ITEM_SPEED: 8589934592,
        CAPABILITY_SET_MEDIA_ITEM_QUEUE: 17179869184,
        CAPABILITY_SET_MEDIA_ITEM_QUEUE_TITLE: 34359738368,
        CAPABILITY_SET_MEDIA_ITEM_QUEUE_ITEM_TITLE: 68719476736,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_METADATA: 137438953472,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_IMAGE: 274877906944,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_URI: 549755813888,
        CAPABILITY_SET_MEDIA_ITEM_MEDIA_ITEM_REPEAT_MODE: 109,
        IOSCategoryOptions: {
          MixWithOthers: 'mixWithOthers',
          DuckOthers: 'duckOthers',
          InterruptSpokenAudioAndMixWithOthers:
            'interruptSpokenAudioAndMixWithOthers',
          AllowBluetooth: 'allowBluetooth',
          AllowBluetoothA2DP: 'allowBluetoothA2DP',
          AllowAirPlay: 'allowAirPlay',
          DefaultToSpeaker: 'defaultToSpeaker',
        },
        IOSCategoryMode: {
          Default: 'default',
          GameChat: 'gameChat',
          Measurement: 'measurement',
          MoviePlayback: 'moviePlayback',
          SpokenAudio: 'spokenAudio',
          VideoChat: 'videoChat',
          VideoRecording: 'videoRecording',
          VoiceChat: 'voiceChat',
          VoicePrompt: 'voicePrompt',
        },
        IOSCategory: {
          Playback: 'playback',
          PlaybackAndRecord: 'playbackAndRecord',
          MultiRoute: 'multiRoute',
          Ambient: 'ambient',
          SoloAmbient: 'soloAmbient',
          Record: 'record',
          PlayAndRecord: 'playAndRecord',
        },
      },
    },
    useTrackPlayerProgress: () => ({
      position: 100,
      duration: 200,
    }),
  }
});